name: 'Canarycage Deploy'
description: 'Deploy service with cage'
author: 'LoiLo'
inputs:
  cage-version:
    description: "Canarycage version"
    default: "3.2.1"
    required: false
  deploy-context:
    description: "Directory path that contains service.json and task-definition.json. Mostly relative path from project root."
    required: true
  region:
    description: "AWS region that cluster exists"
    required: true
  create-deployment:
    description: "Create deployment history on the repository. true or false"
    required: false
  envitonment:
    description: "Arbitrary release environment for github deployment. e.g. development,staging,production... Required by --create-deployment"
    required: false
  github-ref:
    description: "Git tag or branch or sha1 to deploy. Required by --create-deployment."
    required: false
  github-repository:
    description: ":owner/:repo style github repository. Required by --create-deployment. Use github.repository."
    required: false
  github-token:
    description: "Github Token to create deployment on the repository. Required by --create-deployment. Use secrets.GITHUB_TOKEN."
    required: false
runs:
  using: 'node12'
  main: 'lib/index.js'